### ISSUE TITLE
Base URL Support

### ISSUE THREAD

**Issue by samcro1967** [petersem/posterr#98]
Is it possible to configure posterr for a base url for subfolder support behind a reverse proxy?  Trying to get it to response to http://localhost/posterr instead of localhost.

**Comment by petersem** [comment]
@samcro1967 Yes. i have already implemented this feature. In Docker Compose, you set the BASEPATH value.
```
services:
  posterr:
    image: petersem/posterr
    container_name: posterr
    environment:
      TZ: Australia/Brisbane
      BASEPATH: "/posterr"
    volumes:
      - ./docker/posterr/config:/usr/src/app/config
      - ./docker/posterr/custom:/usr/src/app/public/custom
    ports:
      - 9876:3000
    restart: unless-stopped
```

If you are running one of the binaries, you can pass this in as a parameter, along with the port. e.g 
`posterr-win 1234 /posterr`

If this sufficiently answers your question, please let me know and close the issue.
